# Generated by Django 6.0.2 on 2026-03-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.IntegerField(blank=True, null=True)),
                ('issue_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField()),
                ('action', models.CharField(max_length=20)),
                ('actioned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
